# Data Preprocessing Tools

## Importing the libraries

In [58]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [59]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].to_numpy()
y = dataset.iloc[:, -1].to_numpy()
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split


x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

x_train

array([['Spain', nan, 52000.0],
       ['Germany', 40.0, nan],
       ['France', 44.0, 72000.0],
       ['Spain', 38.0, 61000.0],
       ['Spain', 27.0, 48000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 35.0, 58000.0]], dtype=object)

## Taking care of missing data and encoding

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler


numerical_transformer = Pipeline(
    [("impute", SimpleImputer()), ("scale", StandardScaler())]
)
categorical_transformer = Pipeline(
    [("impute", SimpleImputer(strategy="most_frequent")), ("encode", OneHotEncoder())]
)


ct = ColumnTransformer(
    [("cat", categorical_transformer, [0]), ("num", numerical_transformer, [1, 2])],
    remainder="passthrough",
)
x_train = ct.fit_transform(x_train)
x_test = ct.transform(x_test)

np.set_printoptions(suppress=True, precision=4)
x_train

array([[ 0.    ,  0.    ,  1.    ,  0.    , -1.0885],
       [ 0.    ,  1.    ,  0.    , -0.0416,  0.    ],
       [ 1.    ,  0.    ,  0.    ,  0.5408,  0.6238],
       [ 0.    ,  0.    ,  1.    , -0.3328, -0.318 ],
       [ 0.    ,  0.    ,  1.    , -1.9342, -1.431 ],
       [ 1.    ,  0.    ,  0.    ,  1.1231,  1.2231],
       [ 0.    ,  1.    ,  0.    ,  1.4143,  1.5655],
       [ 1.    ,  0.    ,  0.    , -0.7695, -0.5748]])

Encoding the labels

In [62]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)
y_train

array([0, 1, 0, 0, 1, 1, 0, 1])

In [63]:
print(x_train)

[[ 0.      0.      1.      0.     -1.0885]
 [ 0.      1.      0.     -0.0416  0.    ]
 [ 1.      0.      0.      0.5408  0.6238]
 [ 0.      0.      1.     -0.3328 -0.318 ]
 [ 0.      0.      1.     -1.9342 -1.431 ]
 [ 1.      0.      0.      1.1231  1.2231]
 [ 0.      1.      0.      1.4143  1.5655]
 [ 1.      0.      0.     -0.7695 -0.5748]]


In [64]:
print(x_test)

[[ 0.      1.      0.     -1.4975 -0.9173]
 [ 1.      0.      0.     -0.4784  0.1957]]


In [65]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [66]:
print(y_test)

[0 1]
